REM   Script: HACKATHON 2.0
REM   QUESTION 2

CREATE TABLE EMPLOYEES 
(EMPLOYEE_ID INT PRIMARY KEY, 
    NAME VARCHAR(40), 
    MONTHS INT, 
    SALARY INT);

INSERT INTO EMPLOYEES VALUES(12228,'RAHUL',15,10000);

INSERT INTO EMPLOYEES VALUES(33645,'AMIT',1,15000);

INSERT INTO EMPLOYEES VALUES(45692,'ADITI',17,18000);

INSERT INTO EMPLOYEES VALUES(56188,'PAVAN',11,21000);

SELECT * FROM EMPLOYEES;

SELECT COUNT(*) FROM EMPLOYEES;

SELECT SALARY FROM EMPLOYEES WHERE NAME='RAHUL';

SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID=12228;

SELECT SALARY FROM EMPLOYEES WHERE NAME='RAHUL';

UPDATE EMPLOYEES 
SET MONTHS=12 
WHERE NAME='AMIT';

UPDATE EMPLOYEES 
SET MONTHS=12 
WHERE NAME='AMIT';

SELECT * FROM EMPLOYEES;

SELECT SUM(SALARY) FROM EMPLOYEES;

SELECT COUNT(*) 
FROM EMPLOYEES 
WHERE NAME LIKE 'A%';

