CREATE TABLE TRIANGLES 
( TRIANGLE FLOAT, 
    SIDE_A FLOAT, 
    SIDE_B FLOAT, 
    SIDE_C FLOAT);

 INSERT INTO TRIANGLES VALUES (1,20,20,23);

INSERT INTO TRIANGLES VALUES (2,20,20,20);

INSERT INTO TRIANGLES VALUES (3,20,21,22);

INSERT INTO TRIANGLES VALUES (4,13,14,30);

Select * from TRIANGLES;

SELECT SUM(SIDE_A) FROM TRIANGLES;

SELECT * FROM TRIANGLES WHERE SIDE_A = SIDE_B AND SIDE_C;

SELECT * FROM TRIANGLES WHERE SIDE_A = SIDE_B AND SIDE_B=SIDE_C;

SELECT * FROM TRIANGLES WHERE SIDE_A = SIDE_B OR SIDE_B = SIDE_C OR SIDE_A =SIDE_C;

SELECT COUNT(*) FROM TRIANGLES;

SELECT SIDE_B FROM TRIANGLES WHERE ID=3;

SELECT SIDE_B FROM TRIANGLES WHERE TRIANGLE=3;

CREATE TABLE EMPLOYEES 
( EMPLOYEE_ID INT, 
    NAME CHAR, 
    MONTHS INT, 
    SALARY INT );

INSERT INTO EMPLOYEES VALUES(12228,"RAHUL",15,10000);

INSERT INTO EMPLOYEES VALUES(12228,'RAHUL',15,10000);

